services:
  # BAMOE instance 
  maven:
    image: maven:3.9.9-eclipse-temurin-17
    container_name: maven_builder
    volumes:
      - ./SampleHttp:/usr/src/app
      - ./bamoe-maven-repo-91a:/root/.m2/repository
    working_dir: /usr/src/app
    command: mvn clean compile quarkus:dev # mvn clean compile quarkus:dev -D quarkus.http.host=0.0.0.0 # rm -rf /root/.m2/repository &&
    ports:
      - "8080:8080"
      - "5005:5005"
  
  # Kafka Instance
  kafka:
    image: apache/kafka:3.8.1
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - ./data/kafka:/var/lib/kafka/data
  
  # NodeJS Kafka Consumer
  ns-kafka-cnsmr:
    build:
      context: ./servers/ns-kafka-cnsmr
    depends_on:
      - kafka
    environment:
      KAFKA_CLIENT_ID: 'my-app'
      KAFKA_GROUP_ID: 'kogito-kafka-one'
      KAFKA_TOPIC: 'processedPolicies'
      KAFKA_BROKERS: 'kafka:9092'
    volumes:
      - ./servers/ns-kafka-cnsmr:/usr/src/ns-kafka-cnsmr
    command: npm start
    restart: unless-stopped

